version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.0
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build

      - persist_to_workspace:
          root: "build"
          paths:
            - "*"

  deploy:
    docker:
      - image: "circleci/python:2.7"
    steps:
      - attach_workspace:
          at: /tmp/build
      - run: "ls /tmp/build"

      - aws-s3/sync:
          from: /tmp/build
          to: "s3://crest-test-release"
          overwrite: true
      - aws-s3/copy:
          from: /tmp/build/
          to: "s3://crest-test-release"
          arguments: "--recursive"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
